global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "prometheus:9090" ]
  - job_name: 'signal_worker'
    static_configs:
      - targets: ['signal_worker:9105']
  - job_name: 'news-stack'
    metrics_path: /metrics
    static_configs:
      - targets:
          - scraper:8001
          - mapper:8002           # assuming you exposed 8002
          - nlp_worker:8003
          - price_worker:8004
          - signal_worker:8005
          - analytics:8020        # FastAPI analyses, already serving /metrics
